#!/bin/bash
# Run on macOS after Expo prebuild. Produces a simulator screenshot and logs;
# this is a visual diagnostic, not a claim of physical-device rendering success.
set -euo pipefail
cd "$(dirname "$0")/.."
output="$PWD/.expo/live-activity-preview"
mkdir -p "$output"
workspace=$(find "$PWD/ios" -maxdepth 1 -name '*.xcworkspace' -print -quit)
arch=$(uname -m)
sdk=$(xcrun --sdk iphonesimulator --show-sdk-path)

# Xcode's autogenerated extension scheme also builds its React Native host.
# Build only the real widget and its CocoaPods dependencies for this fixture.
node - "$workspace" <<'NODE'
const fs = require('node:fs');
const path = require('node:path');
const xcode = require('xcode');
const ios = path.dirname(process.argv[2]);
const name = fs.readdirSync(ios).find((file) => file.endsWith('.xcodeproj'));
const project = xcode.project(path.join(ios, name, 'project.pbxproj'));
project.parseSync();
const [id] = Object.entries(project.pbxNativeTargetSection()).find(([, target]) =>
  typeof target === 'object' && String(target.name).replace(/^"|"$/g, '') === 'KineSyncLyricsWidget');
const directory = path.join(ios, name, 'xcshareddata', 'xcschemes');
fs.mkdirSync(directory, { recursive: true });
fs.writeFileSync(path.join(directory, 'KineSyncLyricsPreview.xcscheme'), `<?xml version="1.0" encoding="UTF-8"?>
<Scheme LastUpgradeVersion="2600" version="1.3">
  <BuildAction parallelizeBuildables="YES" buildImplicitDependencies="YES">
    <BuildActionEntries>
      <BuildActionEntry buildForTesting="NO" buildForRunning="YES" buildForProfiling="NO" buildForArchiving="NO" buildForAnalyzing="YES">
        <BuildableReference BuildableIdentifier="primary" BlueprintIdentifier="${id}" BuildableName="KineSyncLyricsWidget.appex" BlueprintName="KineSyncLyricsWidget" ReferencedContainer="container:${name}"/>
      </BuildActionEntry>
    </BuildActionEntries>
  </BuildAction>
</Scheme>
`);
NODE
xcodebuild -workspace "$workspace" -scheme KineSyncLyricsPreview \
  -configuration Release -sdk iphonesimulator \
  ARCHS="$arch" ONLY_ACTIVE_ARCH=YES CODE_SIGNING_ALLOWED=NO \
  SYMROOT="$output/products" OBJROOT="$output/objects" \
  > "$output/build.log" 2>&1

app="$output/KineSyncPreview.app"
mkdir -p "$app/PlugIns"
ditto "$output/products/Release-iphonesimulator/KineSyncLyricsWidget.appex" \
  "$app/PlugIns/KineSyncLyricsWidget.appex"
mkdir -p "$output/types"
xcrun --sdk iphonesimulator swiftc -parse-as-library -O -emit-library -static -emit-module \
  -target "$arch-apple-ios16.4-simulator" -sdk "$sdk" \
  -module-name KineSyncActivityTypes \
  -emit-module-path "$output/types/KineSyncActivityTypes.swiftmodule" \
  modules/kinesync-live-activity/ios/types/LyricsActivityAttributes.swift \
  -o "$output/types/libKineSyncActivityTypes.a"
xcrun --sdk iphonesimulator swiftc -parse-as-library -O \
  -target "$arch-apple-ios16.4-simulator" -sdk "$sdk" \
  -module-name KineSyncLiveActivity \
  -I "$output/types" "$output/types/libKineSyncActivityTypes.a" \
  scripts/live-activity-preview/PreviewApp.swift -o "$app/KineSyncPreview"

python3 - "$app" <<'PY'
import plistlib, sys
from pathlib import Path
app = Path(sys.argv[1])
widget = plistlib.loads((app / 'PlugIns/KineSyncLyricsWidget.appex/Info.plist').read_bytes())
host = {
    'CFBundleExecutable': 'KineSyncPreview', 'CFBundleName': 'KineSync Preview',
    'CFBundleIdentifier': widget['CFBundleIdentifier'].rsplit('.', 1)[0],
    'CFBundlePackageType': 'APPL', 'CFBundleVersion': widget['CFBundleVersion'],
    'CFBundleShortVersionString': widget['CFBundleShortVersionString'],
    'CFBundleSupportedPlatforms': ['iPhoneSimulator'], 'MinimumOSVersion': '16.4',
    'NSSupportsLiveActivities': True, 'UIDeviceFamily': [1], 'UILaunchScreen': {},
    'UIApplicationSceneManifest': {'UIApplicationSupportsMultipleScenes': False},
}
(app / 'Info.plist').write_bytes(plistlib.dumps(host))
PY
codesign --force --sign - "$app/PlugIns/KineSyncLyricsWidget.appex"
codesign --force --sign - "$app"
bundle=$(/usr/libexec/PlistBuddy -c 'Print CFBundleIdentifier' "$app/Info.plist")
xcrun simctl list devices available -j > "$output/devices.json"
device=$(python3 - "$output/devices.json" <<'PY'
import json, sys
devices = json.load(open(sys.argv[1]))['devices']
for runtime in sorted(devices, reverse=True):
    for device in devices[runtime]:
        if 'iOS-27-' in runtime and 'iPhone' in device['name'] and 'Pro' in device['name'] and device['isAvailable']:
            print(device['udid'])
            sys.exit(0)
raise SystemExit('No iOS 27 Dynamic Island iPhone simulator available')
PY
)
xcrun simctl boot "$device" || true
xcrun simctl bootstatus "$device" -b
xcrun simctl ui "$device" appearance light
xcrun simctl install "$device" "$app"
xcrun simctl spawn "$device" log stream --level info --style compact \
  --predicate 'subsystem == "dev.kineticron.KineSync.live-activity"' > "$output/runtime.log" 2>&1 &
log_pid=$!
trap 'kill "$log_pid" 2>/dev/null || true; xcrun simctl shutdown "$device" || true' EXIT
xcrun simctl launch "$device" "$bundle"
sleep 5
# Another app exposes the compact Island, as it would appear during playback.
xcrun simctl launch "$device" com.apple.Preferences
sleep 5
xcrun simctl io "$device" screenshot "$output/compact-island.png"
python3 scripts/check-live-activity-preview.py "$output/compact-island.png"
printf 'Preview device: %s\nAttributes module: KineSyncActivityTypes (host and widget)\n' "$device" > "$output/preview.txt"
