#!/usr/bin/env node
// Download native release assets only after checking GitHub's SHA-256 digest
// (or the versioned manifest generated by the native build workflow). Files
// are checked before they are installed and are renamed atomically.

const fs = require("node:fs");
const path = require("node:path");
const crypto = require("node:crypto");
const https = require("node:https");

const PKG = require("../package.json");
const POLICY = require("../native/native-assets-manifest.json");
const REPO = "Kineticron/KineSync";
const TAG = `v${PKG.version}`;
const MANIFEST_ASSET = `native-assets-v${PKG.version}.json`;
const MAX_MANIFEST_BYTES = 64 * 1024;
const ALLOWED_HOSTS = new Set([
  "api.github.com",
  "github.com",
  "objects.githubusercontent.com",
  "github-releases.githubusercontent.com",
  // GitHub's release download endpoint currently redirects to this host.
  // Keep the allow-list explicit rather than accepting arbitrary HTTPS hosts.
  "release-assets.githubusercontent.com",
]);

const NATIVE_MEDIA_DIR = path.join(__dirname, "..", "native", "windows-media-session");
const SEEK_HELPER_OUT = path.join(__dirname, "..", "native", "spotify-seek-helper", "bin", "Release", "net9.0-windows10.0.19041.0");

// { destPath: assetName }
const ASSETS = {
  [path.join(NATIVE_MEDIA_DIR, "windows_media_session.node")]: "windows_media_session.node",
  [path.join(SEEK_HELPER_OUT, "spotify-seek-helper.dll")]: "spotify-seek-helper.dll",
  [path.join(SEEK_HELPER_OUT, "spotify-seek-helper.runtimeconfig.json")]: "spotify-seek-helper.runtimeconfig.json",
  [path.join(SEEK_HELPER_OUT, "Microsoft.Windows.SDK.NET.dll")]: "Microsoft.Windows.SDK.NET.dll",
  [path.join(SEEK_HELPER_OUT, "WinRT.Runtime.dll")]: "WinRT.Runtime.dll",
};

function sourceBuildMessage() {
  return "Run 'npm run build:native' in DesktopBridge to build native artifacts from source (or set KINESYNC_NATIVE_SOURCE_BUILD=1 to skip this downloader explicitly).";
}

function assertHttpsGithubUrl(value) {
  const parsed = new URL(value);
  if (parsed.protocol !== "https:" || !ALLOWED_HOSTS.has(parsed.hostname)) {
    throw new Error(`Refusing download URL outside GitHub HTTPS hosts: ${value}`);
  }
  return parsed.toString();
}

function httpsGet(url, { maxBytes, redirectCount = 0 } = {}) {
  const safeUrl = assertHttpsGithubUrl(url);
  if (redirectCount > 5) throw new Error("Too many redirects");
  return new Promise((resolve, reject) => {
    const req = https.get(safeUrl, { headers: { "User-Agent": "KineSync-postinstall" } }, (res) => {
      if (res.statusCode >= 300 && res.statusCode < 400 && res.headers.location) {
        res.resume();
        resolve(httpsGet(new URL(res.headers.location, safeUrl).toString(), { maxBytes, redirectCount: redirectCount + 1 }));
        return;
      }
      if (res.statusCode !== 200) {
        res.resume();
        reject(new Error(`HTTP ${res.statusCode} for ${safeUrl}`));
        return;
      }
      const advertised = Number(res.headers["content-length"]);
      if (maxBytes && Number.isSafeInteger(advertised) && advertised > maxBytes) {
        res.resume();
        reject(new Error(`Content-Length ${advertised} exceeds ${maxBytes} bytes`));
        return;
      }
      const chunks = [];
      let total = 0;
      res.on("data", (chunk) => {
        total += chunk.length;
        if (maxBytes && total > maxBytes) {
          res.destroy(new Error(`Response exceeds ${maxBytes} bytes`));
          return;
        }
        chunks.push(chunk);
      });
      res.on("end", () => resolve(Buffer.concat(chunks, total)));
      res.on("error", reject);
    });
    req.setTimeout(30_000, () => req.destroy(new Error("Request timed out")));
    req.on("error", reject);
  });
}

function sha256(buffer) {
  return crypto.createHash("sha256").update(buffer).digest("hex");
}

function normalizeDigest(value) {
  if (typeof value !== "string") return null;
  const digest = value.replace(/^sha256:/i, "").toLowerCase();
  return /^[a-f0-9]{64}$/.test(digest) ? digest : null;
}

function readPolicy() {
  if (POLICY.schemaVersion !== 1 || !POLICY.assets) throw new Error("Invalid native asset size policy");
  for (const name of Object.values(ASSETS)) {
    const maxBytes = POLICY.assets[name]?.maxBytes;
    if (!Number.isSafeInteger(maxBytes) || maxBytes <= 0) throw new Error(`Missing maxBytes policy for ${name}`);
  }
}

async function fetchRelease() {
  const apiUrl = `https://api.github.com/repos/${REPO}/releases/tags/${TAG}`;
  const release = JSON.parse((await httpsGet(apiUrl, { maxBytes: 1024 * 1024 })).toString("utf8"));
  if (release.tag_name !== TAG || !Array.isArray(release.assets)) throw new Error(`Release metadata did not match ${TAG}`);
  return release.assets;
}

function indexAssets(assets) {
  return Object.fromEntries(assets.map((asset) => [asset.name, asset]));
}

async function downloadChecked(asset, expected, maxBytes) {
  const url = asset?.browser_download_url;
  if (!url) throw new Error(`Asset ${asset?.name || "(unknown)"} has no download URL`);
  const apiDigest = normalizeDigest(asset.digest);
  if (!expected || !normalizeDigest(expected.sha256)) throw new Error(`No trusted SHA-256 digest is available for ${asset.name}`);
  const expectedHash = normalizeDigest(expected.sha256);
  if (apiDigest && apiDigest !== expectedHash) throw new Error(`GitHub digest disagrees with manifest for ${asset.name}`);
  const expectedSize = expected.size;
  if (!Number.isSafeInteger(expectedSize) || expectedSize < 1 || expectedSize > maxBytes) throw new Error(`Invalid expected size for ${asset.name}`);
  if (Number.isSafeInteger(asset.size) && asset.size !== expectedSize) throw new Error(`GitHub size disagrees with manifest for ${asset.name}`);
  const data = await httpsGet(assertHttpsGithubUrl(url), { maxBytes });
  if (data.length !== expectedSize) throw new Error(`Downloaded size ${data.length} disagrees with manifest for ${asset.name}`);
  if (sha256(data) !== expectedHash) throw new Error(`SHA-256 verification failed for ${asset.name}`);
  return data;
}

function installAtomically(destPath, data) {
  fs.mkdirSync(path.dirname(destPath), { recursive: true });
  const tempPath = `${destPath}.tmp-${process.pid}-${crypto.randomBytes(8).toString("hex")}`;
  try {
    fs.writeFileSync(tempPath, data, { flag: "wx", mode: 0o644 });
    fs.renameSync(tempPath, destPath);
  } finally {
    try { fs.unlinkSync(tempPath); } catch (err) { if (err.code !== "ENOENT") throw err; }
  }
}

async function expectedFromManifest(byName) {
  const manifestAsset = byName[MANIFEST_ASSET];
  if (!manifestAsset) return null;
  const apiDigest = normalizeDigest(manifestAsset.digest);
  if (!apiDigest) throw new Error(`${MANIFEST_ASSET} has no GitHub SHA-256 digest; refusing an unverified manifest`);
  const data = await httpsGet(manifestAsset.browser_download_url, { maxBytes: MAX_MANIFEST_BYTES });
  if (Number.isSafeInteger(manifestAsset.size) && data.length !== manifestAsset.size) throw new Error("Downloaded manifest size disagrees with GitHub metadata");
  if (sha256(data) !== apiDigest) throw new Error("Native manifest SHA-256 verification failed");
  const manifest = JSON.parse(data.toString("utf8"));
  if (manifest.schemaVersion !== 1 || manifest.manifestVersion !== PKG.version || manifest.releaseTag !== TAG || !manifest.assets) {
    throw new Error(`Native manifest does not describe ${TAG}`);
  }
  for (const name of Object.values(ASSETS)) {
    const entry = manifest.assets[name];
    if (!entry || !normalizeDigest(entry.sha256) || !Number.isSafeInteger(entry.size) || entry.size < 1) {
      throw new Error(`Native manifest is missing a valid entry for ${name}`);
    }
  }
  return manifest.assets;
}

function isExplicitlyEnabled(value) {
  return ["1", "true", "yes"].includes(String(value || "").trim().toLowerCase());
}

async function main() {
  if (process.platform !== "win32") return;
  if (isExplicitlyEnabled(process.env.SKIP_POSTINSTALL) || isExplicitlyEnabled(process.env.KINESYNC_NATIVE_SOURCE_BUILD)) {
    console.warn(`[postinstall] Native downloader skipped by explicit source-build escape. ${sourceBuildMessage()}`);
    return;
  }
  readPolicy();
  // Local builds are valid and should not be replaced by downloaded files.
  if (Object.keys(ASSETS).every((file) => fs.existsSync(file))) return;

  let byName;
  let releaseManifest;
  try {
    byName = indexAssets(await fetchRelease());
    releaseManifest = await expectedFromManifest(byName);
  } catch (err) {
    console.warn(`[postinstall] Could not obtain verified release metadata for ${TAG}: ${err.message}`);
    console.warn(`[postinstall] ${sourceBuildMessage()}`);
    return;
  }

  // Verify every missing artifact before changing the install tree. This avoids
  // leaving a partially hydrated native install after a transient network error.
  const staged = [];
  for (const [destPath, assetName] of Object.entries(ASSETS)) {
    if (fs.existsSync(destPath)) continue;
    const asset = byName[assetName];
    const maxBytes = POLICY.assets[assetName].maxBytes;
    // New releases carry the versioned manifest. For older releases, GitHub's
    // API digest is accepted directly so existing releases remain usable.
    const expected = releaseManifest?.[assetName] || { sha256: asset?.digest, size: asset?.size };
    try {
      process.stdout.write(`[postinstall] Verifying and downloading ${assetName}...`);
      const data = await downloadChecked(asset, expected, maxBytes);
      staged.push({ destPath, data });
      console.log(" done.");
    } catch (err) {
      console.warn(` failed: ${err.message}`);
      return;
    }
  }
  for (const { destPath, data } of staged) installAtomically(destPath, data);
  if (staged.length > 0) console.log(`[postinstall] Installed ${staged.length} verified native artifact(s).`);
}

main().catch((err) => {
  console.warn(`[postinstall] Unexpected error: ${err.message}`);
  console.warn(`[postinstall] ${sourceBuildMessage()}`);
});
